name: Deploy HEXO site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          run: npm install
      
      - name: Build site
        run: npx hexo generate
      
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /public
