name: Hexo Deploy # 部署的名称
on:
  push:
    branches:
      - main # 触发部署的分支名称

jobs:
  build-and-deploy: # 定义作业的名称
    runs-on: ubuntu-latest # 指定运行环境

    steps:
      - name: Checkout # 拉取代码
        uses: actions/checkout@v2

      - name: Setup Node.js # 安装 Node.js 和 Hexo
        uses: actions/setup-node@v2
        with:
          node-version: 14
        run: |
          npm install -g hexo-cli
          npm install

      - name: Build # 构建静态网站
        run: |
          hexo clean
          hexo generate

      - name: Deploy # 部署网站
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }} # 用于发布的 Token，请确保已设置 secrets
          publish_dir: ./public # 部署目录
          cname: wyblog11.github.io # 如果你有自定义域名，则在此处填写
