# workflow name
name: actions single


on: [push, repository_dispatch]

# YQ_TOKEN
# YUQUE_GIT_HEXO
jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: 安装 Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
      - name: 开始部署
        env:
          HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}    # 这个就是Source仓库的私钥
        run: |
          git config --global user.email "3227988255@qq.com"
          git config --global user.name "wyblog11"
          npm install yarn hexo gulp -g
          yarn
          hexo g
          hexo algolia

      - name: 部署到blog仓库
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          repository-name: 612901/612901.github.io
          branch: main
          folder: public
          commit-message: '${{ github.event.head_commit.message }} Updated By Github Actions'
